### ISSUE TITLE
will all plugins will be submitted?

### ISSUE THREAD

**Issue by legoboy0215** [ItalianDevs4PM/Projects#1]
Will it?

**Comment by fycarman** [comment]
Yes,all plugin will be submitted on PocketMine forum. TNTRun is coming! Stay tuned! :)

**Comment by legoboy0215** [comment]
:) Neat group you have here... BTW, why isn't EvolSoft\Flavius12 here?

**Comment by Flavius12** [comment]
I'm also here :D

**Comment by legoboy0215** [comment]
Oooo. Lol
