### ISSUE TITLE
Why was I tagged in this Project?

### ISSUE THREAD

**Issue by TekkitCommando** [ItalianDevs4PM/Projects#2]
I apparently was tagged on this project?

**Comment by luca28pet** [comment]
I'm sorry for this.
@RandomAltThing did that while we were arguing and he wanted to show off the developers he is working with so he tagged you

**Comment by TekkitCommando** [comment]
Ok np. I hope whatever this project is, that it goes well :)

**Comment by luca28pet** [comment]
Thanks mate :+1:
